# Generated by Django 3.1.7 on 2021-08-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='text',
        ),
    ]
